# Generated by Django 3.1.7 on 2021-04-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210414_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='houserules',
            new_name='house_rules',
        ),
    ]
