# Generated by Django 3.1.7 on 2021-05-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210527_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='uer',
            new_name='user',
        ),
    ]
